define ->
  class Eventful
    @constructor: ->
      @bus = $(document.createElement 'div')
    bind: (args...)-> @bus.bind args...
    one: (args...)-> @bus.one args...
    unbind: (args...)-> @bus.unbind args...
